# Form implementation generated from reading ui file 'ui.ui'
#
# Created by: PyQt6 UI code generator 6.2.2
#
# WARNING: Any manual changes made to this file will be lost when pyuic6 is
# run again.  Do not edit this file unless you know what you are doing.


from PyQt6 import QtCore, QtGui, QtWidgets


class Ui_Form(object):
    def setupUi(self, Form):
        Form.setObjectName("Form")
        Form.resize(200, 250)
        Form.setMinimumSize(QtCore.QSize(200, 250))
        Form.setMaximumSize(QtCore.QSize(200, 250))
        self.verticalLayout = QtWidgets.QVBoxLayout(Form)
        self.verticalLayout.setObjectName("verticalLayout")
        self.intvalid = QtGui.QIntValidator()
        self.input1 = QtWidgets.QLineEdit(Form)
        self.input1.setObjectName("input1")
        self.input1.setValidator(self.intvalid)
        self.verticalLayout.addWidget(self.input1)
        self.input2 = QtWidgets.QLineEdit(Form)
        self.input2.setObjectName("input2")
        self.input2.setValidator(self.intvalid)

        self.verticalLayout.addWidget(self.input2)
        spacerItem = QtWidgets.QSpacerItem(20, 20, QtWidgets.QSizePolicy.Policy.Minimum, QtWidgets.QSizePolicy.Policy.Maximum)
        self.verticalLayout.addItem(spacerItem)
        self.horizontalLayout = QtWidgets.QHBoxLayout()
        self.horizontalLayout.setObjectName("horizontalLayout")
        self.plus = QtWidgets.QPushButton(Form)
        self.plus.setObjectName("plus")
        self.horizontalLayout.addWidget(self.plus)
        self.sub = QtWidgets.QPushButton(Form)
        self.sub.setObjectName("sub")
        self.horizontalLayout.addWidget(self.sub)
        self.verticalLayout.addLayout(self.horizontalLayout)
        spacerItem1 = QtWidgets.QSpacerItem(20, 50, QtWidgets.QSizePolicy.Policy.Minimum, QtWidgets.QSizePolicy.Policy.Maximum)
        self.verticalLayout.addItem(spacerItem1)
        self.output = QtWidgets.QLineEdit(Form)
        self.output.setObjectName("output")
        self.verticalLayout.addWidget(self.output)


        self.plus.clicked.connect(self.plus_func)
        self.sub.clicked.connect(self.sub_func)

        self.retranslateUi(Form)
        QtCore.QMetaObject.connectSlotsByName(Form)

    def retranslateUi(self, Form):
        _translate = QtCore.QCoreApplication.translate
        Form.setWindowTitle(_translate("Form", "Calculator"))
        self.input1.setPlaceholderText(_translate("Form", "INPUT 1"))
        self.input2.setPlaceholderText(_translate("Form", "INPUT 2"))
        self.plus.setText(_translate("Form", "+"))
        self.sub.setText(_translate("Form", "-"))
        self.output.setPlaceholderText(_translate("Form", "OUTPUT"))

    def plus_func(self):
        data_1 = int(self.input1.text())
        data_2 = int(self.input2.text())
        self.output.setText(f"{data_1 + data_2}")

    def sub_func(self):
        data_1 = int(self.input1.text())
        data_2 = int(self.input2.text())
        self.output.setText(f"{data_1 - data_2}")
if __name__ == "__main__":
    import sys
    app = QtWidgets.QApplication(sys.argv)
    Form = QtWidgets.QWidget()
    ui = Ui_Form()
    ui.setupUi(Form)
    Form.show()
    sys.exit(app.exec())
