# Form implementation generated from reading ui file '.\myproject.ui'
#
# Created by: PyQt6 UI code generator 6.2.2
#
# WARNING: Any manual changes made to this file will be lost when pyuic6 is
# run again.  Do not edit this file unless you know what you are doing.


from PyQt6 import QtCore, QtGui, QtWidgets


class Ui_Dialog(object):
    def setupUi(self, Dialog):
        Dialog.setObjectName("Dialog")
        Dialog.resize(614, 349)
        self.verticalLayout = QtWidgets.QVBoxLayout(Dialog)
        self.verticalLayout.setObjectName("verticalLayout")
        self.listWidget = QtWidgets.QListWidget(Dialog)
        font = QtGui.QFont()
        font.setPointSize(20)
        self.listWidget.setFont(font)
        self.listWidget.setObjectName("listWidget")
        self.verticalLayout.addWidget(self.listWidget)
        self.horizontalLayout = QtWidgets.QHBoxLayout()
        self.horizontalLayout.setObjectName("horizontalLayout")
        self.add_btn = QtWidgets.QPushButton(Dialog)
        font = QtGui.QFont()
        font.setPointSize(20)
        self.add_btn.setFont(font)
        self.add_btn.setObjectName("add_btn")
        self.horizontalLayout.addWidget(self.add_btn)
        self.edit_btn = QtWidgets.QPushButton(Dialog)
        font = QtGui.QFont()
        font.setPointSize(20)
        self.edit_btn.setFont(font)
        self.edit_btn.setObjectName("edit_btn")
        self.horizontalLayout.addWidget(self.edit_btn)
        self.remove_btn = QtWidgets.QPushButton(Dialog)
        font = QtGui.QFont()
        font.setPointSize(20)
        self.remove_btn.setFont(font)
        self.remove_btn.setObjectName("remove_btn")
        self.horizontalLayout.addWidget(self.remove_btn)
        self.sort_btn = QtWidgets.QPushButton(Dialog)
        font = QtGui.QFont()
        font.setPointSize(20)
        self.sort_btn.setFont(font)
        self.sort_btn.setObjectName("sort_btn")
        self.horizontalLayout.addWidget(self.sort_btn)
        self.verticalLayout.addLayout(self.horizontalLayout)

        self.retranslateUi(Dialog)
        QtCore.QMetaObject.connectSlotsByName(Dialog)

    def retranslateUi(self, Dialog):
        _translate = QtCore.QCoreApplication.translate
        Dialog.setWindowTitle(_translate("Dialog", "Dialog"))
        self.add_btn.setText(_translate("Dialog", "add"))
        self.add_btn.clicked.connect(self.add_item)

        self.edit_btn.setText(_translate("Dialog", "edit"))
        self.edit_btn.clicked.connect(self.edit_item)

        self.remove_btn.setText(_translate("Dialog", "remove"))
        self.remove_btn.clicked.connect(self.remove_item)

        self.sort_btn.setText(_translate("Dialog", "Sort"))
        self.sort_btn.clicked.connect(self.sort_items)

    def add_item(self):
        row = self.listWidget.currentRow()
        data, ok = QtWidgets.QInputDialog.getText(Dialog, 'Title Add Item', 'Text Add item')
        if ok and data:
            # self.listWidget.addItem(data)
            self.listWidget.insertItem(row, data)

    def remove_item(self):
        row = self.listWidget.currentRow()
        question = QtWidgets.QMessageBox.question(Dialog, 'Title', 'Text',
                          QtWidgets.QMessageBox.StandardButton.Ok | QtWidgets.QMessageBox.StandardButton.No)
        if question == QtWidgets.QMessageBox.StandardButton.Ok:
            self.listWidget.takeItem(row)

    def edit_item(self):
        row = self.listWidget.currentRow()
        data, ok = QtWidgets.QInputDialog.getText(Dialog, 'title', 'text', QtWidgets.QLineEdit.EchoMode.Normal,
                                                  self.listWidget.item(row).text())
        if ok and data:
            self.listWidget.item(row).setText(data)

    def sort_items(self):
        self.listWidget.sortItems()

if __name__ == "__main__":
    import sys
    app = QtWidgets.QApplication(sys.argv)
    Dialog = QtWidgets.QDialog()
    ui = Ui_Dialog()
    ui.setupUi(Dialog)
    Dialog.show()
    sys.exit(app.exec())
